# Generated by Django 4.2.4 on 2023-10-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
